# Generated by Django 4.2.5 on 2023-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0002_usermodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
