# Generated by Django 4.2.5 on 2023-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0002_educationalmodule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
