# Generated by Django 4.2.5 on 2023-09-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_modules', '0003_usermodule_is_payed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModule',
        ),
    ]
