# Generated by Django 4.2.5 on 2023-09-14 17:58

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.manager.UserManager()),
            ],
        ),
    ]
