# Generated by Django 4.2.5 on 2023-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_card',
            field=models.CharField(default=None, max_length=20, verbose_name='банковская карта'),
        ),
    ]
