# Generated by Django 4.2.5 on 2023-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_card',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='банковская карта'),
        ),
    ]
