# Generated by Django 4.2.5 on 2023-10-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=19, verbose_name='Номер карты')),
                ('date', models.CharField(max_length=5, verbose_name='Дата')),
                ('csv', models.IntegerField(verbose_name='csv')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
    ]
