# Generated by Django 4.2.5 on 2023-10-01 16:14

import bank_card.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='csv',
            field=models.IntegerField(validators=[bank_card.validators.validate_csv], verbose_name='csv'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='date',
            field=models.CharField(max_length=5, validators=[bank_card.validators.validate_date_card], verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='number_card',
            field=models.CharField(max_length=19, unique=True, validators=[bank_card.validators.validate_card_number], verbose_name='Номер карты'),
        ),
    ]
