# Generated by Django 4.2.5 on 2023-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_modules', '0003_educationalmodule_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.FileField(upload_to='materials/', verbose_name='Материал')),
                ('educational_module', models.ManyToManyField(to='educational_modules.educationalmodule', verbose_name='Образовательный модуль')),
            ],
        ),
    ]
